name: Apply Terraform
run-name: "Apply Terraform"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: ''
        options:
          - DEV
          - STAGING
          - PROD

jobs:
  deploy-infra-dev:
    name: Validate-terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.x
    
    - name: 'Google Auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets[format('{0}_GCP_CREDENTIALS', github.event.inputs.environment)] }}

  
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Terraform Init
      run: terraform init    
    
    - name: Terraform Validate
      run: terraform validate
    
    - name: Write Terraform Variables to File
      env:
        TF_VAR: ${{ secrets[format('TF_VARS_{0}', github.event.inputs.environment)] }}
      run: |
        echo "TF_VAR='${TF_VAR}'" > "${{ github.event.inputs.environment }}.tfvars"
      shell: bash

    - name: Terraform Apply
      run: terraform apply -var-file="${{github.event.inputs.environment}}.tfvars" -auto-approve
